const roomsState = {
  room1: {
    id: 1,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room2: {
    id: 2,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room3: {
    id: 3,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room4: {
    id: 4,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room5: {
    id: 5,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room6: {
    id: 6,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room7: {
    id: 7,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room8: {
    id: 8,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room9: {
    id: 9,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
  room10: {
    id: 10,
    likedRecipes: [],
    users: [],
    chat: [],
    likedRecipeLimit: false,
    wonRecipe: [],
  },
};

module.exports = { roomsState };
